### PR TITLE
Donate Block: Manual Mode

### PR DESCRIPTION
**Pull request by jeffersonrabb**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Normally the Donate block derives tiering and pricing data from the Newspack Plugin's Reader Revenue Wizard. In some circumstances publishers need to control these settings on a per-block basis. This PR adds a "Configure Manually" toggle to the Donate block's Inspector Controls. When switched on, the tiering and pricing of the block can be set manually. 

Closes https://github.com/Automattic/newspack-blocks/issues/308

Screen Shot 2019-12-22 at 5 48 36 PM

### How to test the changes in this Pull Request:

1. In Newspack Plugin be sure the Reader Revenue Wizard is fully configured (even in Manual mode the block gets the currency symbol and submission URL from the Wizard).
2. Add a Donate block to a page or post, then in the sidebar switch on "Configure Manually."
3. WIth Tiered Mode off verify there is one price field shown in the sidebar, and changing it updates the block. The MONTHLY amount should match the price field's value. ONE-TIME and ANNUALLY should be the value * 12.
4. Publish the block and verify the prices are the same on the front end.
5. Edit the post and switch Tiered on. Verify there are now three price fields and changing any updates the block.
6. Publish the block and verify the prices are the same on the front end.
7. Switch off "Configure manually," and verify the block reverts to settings from the Reader Revenue Wizard. Publish and verify these settings are seen in the front end.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by philipjohn** [comment]
This is looking good!

One bit that is a little clawing is that as soon as you toggle "configure manually" all the values reset to zero. I'd expected that they'd all remain as they are for me to adjust from the default values.

When I started messing around with numbers I saw some weird behaviour thanks to the calculations being made to create the one-time and annual figures. Not sure if this is a wider problem or specific to this new feature.
Screenshot from 2019-12-23 13-43-36

It can get pretty weird :laughing: 
Screenshot from 2019-12-23 13-45-23

I was able to go negative on the suggested donation too:
Screenshot from 2019-12-23 13-46-23

**Comment by jeffersonrabb** [comment]
Good catches. Looks like you can do the same things in the Newspack Plugin Reader Revenue Wizard (negative values, 3+ decimal places). I'll add enforcement of positive numbers with maximum 2 decimal places.

**Comment by jeffersonrabb** [comment]
> One bit that is a little clawing is that as soon as you toggle "configure manually" all the values reset to zero. I'd expected that they'd all remain as they are for me to adjust from the default values.

This is resolved in https://github.com/Automattic/newspack-blocks/pull/311/commits/3ca42d0d96ff94f61d6da83ffa77dc645e960ecd. When the manual mode is switched on for the first time, the manual prices are copied over from the values that were set in the Reader Revenue Wizard.

**Comment by jeffersonrabb** [comment]
> When I started messing around with numbers I saw some weird behaviour thanks to the calculations being made to create the one-time and annual figures. Not sure if this is a wider problem or specific to this new feature.

Made a series of changes so that negative prices cannot be input, inputs are limited to 2 decimal places, and the display of prices will be 2 decimal places if needed and none if the price is an integer.

**Comment by jeffersonrabb** [comment]
Thank you both for looking!

**Pull request merged**
