### PR TITLE
help.newspack.com doc links

### PR DESCRIPTION
**Pull request by gamebits**
Updates all newspack.pub documentation references in code to help.newspack.com.

### CODE REVIEW

**Review by leogermani — APPROVED** [review]
I've checked that the new URLs exist and they look good.

Not related to this PR but do we really want these URLs to be i18n ? And if so, the text domain is missing from the `__()` calls...

I think we could drop the usage of i18n there, since we don't have a standardized way of offering different URLs for different languages, nor we have the documentation in different language...

**Comment by miguelpeixe** [comment]
The diff breaks lint as well. The linter is probably requiring a line break due to the increase in the number of characters.

**Comment by leogermani** [comment]
> The diff breaks lint as well. The linter is probably requiring a line break due to the increase in the number of characters.

I went ahead and fixed it

**Review by miguelpeixe — APPROVED** [review]
🙌

**Pull request merged**
