### PR TITLE
fix(ras-acc): add check for if RAS is enabled to allow checkout

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR makes it possible to use the modal checkout when RAS isn't enabled, to match the current behaviour on trunk.

The main difference between the RAS-based checkout is that the initial checkout screen will require you to fill our the email address with the other billing details, since it won't be pre-populated from the Sign In/Sign Up screen.

See: 1207817176293825-as-1208164200882316

### How to test the changes in this Pull Request:

1. Start on a test site without RAS enabled, or disable it by running `wp option delete newspack_reader_activation_enabled`.
2. Set up three blocks: a regular Checkout Button block, one with a variable product, and a Donate block.
3. On epic/ras-acc in an incognito window, try to run the checkout in any of the blocks; only the initial variation picker will open.
4. Apply this PR and run `npm run build`.
5. In the incognito window, run through each checkout and confirm it works.
6. Enable RAS (run `wp option update newspack_reader_activation_enabled 1` or use the wizard), or re-test this PR on a second test site with RAS enabled.
7. Smoke test the checkout flows as a new reader and as a logged in reader and confirm that you get the Sign In prompts at the appropriate points, and that the checkout works as usual.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by laurelfulford** [comment]
Switching this back to draft mode -- looks like it's not working as I'd hoped!

Edited to add: It was a variable name change at the last moment 🤦‍♀️ Working now!

**Review by chickenn00dle — CHANGES_REQUESTED** [review]
Hmm. It feels strange that the openAuthModal method would be available when ras is not enabled. I think a cleaner solution might be to move this logic into the main plugin and make sure ras is enabled before making the `openAuthModal` function available. This would also resolve things in blocks since when that function is not present, modal checkout will just open normally.

WDYT?

**Comment by laurelfulford** [comment]
Oh yeah, that would be nicer 😄 I'll dig into that tomorrow!

**Comment by laurelfulford** [comment]
Replaced with https://github.com/Automattic/newspack-plugin/pull/3396, and closing -- thanks @chickenn00dle!

**Pull request closed without merging**
