### PR TITLE
Update Column Block styles for WordPress 5.9.

### LINKED ISSUE #1018: Column block spacing changed in 5.9
This may be something we need to address in the theme as well as the blocks:

In WP 5.9 the spacing on the column block changed.

This is noticable because the gutter between columns has increased. 

It also causes the columns to be slightly "offset" when you use the block styles to reorder the columns on desktop - the first column is too far to the left. In the screenshot below, the second column block has the 'Move first column to second' style applied:

image

Edited to add: the border style also looks a bit "off" with this update -- the border 

image

image

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

In the Newspack Blocks suite, we have some column block styles that:

1. Update the default column block styles, to not wrap until they hit the mobile breakpoint.
2. Allow you to add borders to the columns.
3. Allow you to reorder the columns on desktop.

Changes coming in WP 5.9 to add the option to not wrap columns on mobile have overridden some of our own styles. This PR hopefully sorts them out and gets them working again, without causing issues in 5.8.

Closes #1018 and #1019

### How to test the changes in this Pull Request:

This will be easiest to test if you can work with two test sites and compare them: one running WordPress 5.8.X, and the other running the 5.9 RC.

1. In the test site running 5.9 RC, copy [this test content](https://github.com/Automattic/newspack-blocks/files/7885188/columns-59.txt) to the editor, or add a bunch of column blocks with different settings. Change the page you test to use the one column wide template.
2. In the test site running 5.8.X, copy [this test content](https://github.com/Automattic/newspack-blocks/files/7885189/columns-58.txt) to the editor, or add a bunch of column blocks with different settings. Change the page you test to use the one column wide template.
3. Apply this PR to both sites and run `npm run build`.
4. Apply this theme PR to both sites and run `npm run build` - it updates a couple styles in the theme: https://github.com/Automattic/newspack-theme/pull/1670
5. View and compare both posts at different breakpoints. Things to look for include:

* Making sure the columns block doesn't wrap on mobile when its set not to on the 5.9 site.
* That the columns styles and spacing look consistent between the different sections.
* That the border styles and spacing look consistent between the different sections.

Here are some examples of how things should look:

**WordPress 5.9**

Regular columns:
image

"Don't stack on mobile" setting (the first column doesn't have this checked, and the second one does)

image

Reordered blocks: 

image

Columns blocks with borders: 

image

**WordPress 5.8**

Regular columns:
image

Reordered columns:

image

Columns with borders: 

image

6. Review things in the editor and make sure things look fairly consistent between the two versions.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
I can still see some significant differences between 5.9 and 5.8, here's what I've identified:

| 5.9 RC2 | 5.8 | Comment |
| - | - | - |
| image | image | Grid is not behaving the same on equal viewport |
| image | image | Difference in grid also causing a border out of place |
| image | image | Flex gap disrupting border alignment |
| image | | Column containers have bigger margin between them, which doesn't occur on 5.8 |

**Comment by dkoo** [comment]
I'm not seeing the same thing as @miguelpeixe. I found it difficult to compare apples to apples with two different sets of content, so what I did was to paste both sets of content into a single post on both 5.8 and 5.9 sites.

* [5.9 test site](https://vivacious-shark.jurassic.ninja/2022/01/18/columns-test/)
* [5.8 test site](https://equivalent-lynx.jurassic.ninja/2022/01/18/columns-test/)

With both sites using the same content, it's easier to see that the styles match well across both WP versions. The main differences I see are:

- The "Don't stack on mobile" columns do stack in WP 5.8 (as expected, since this is a new feature in 5.9)
- Slight differences in spacing in the editor, but not on the front-end

@miguelpeixe can you review these two test sites and let us know what you see?

**Review by miguelpeixe — APPROVED** [review]
I'm sorry about that! I was not on 5.9 RC2's Gutenberg. I now can confirm that the columns are behaving as expected!

**Comment by laurelfulford** [comment]
Thank you @miguelpeixe and @dkoo! 🙌

**Pull request merged**
