### PR TITLE
WIP Article Block Height: Add input for setting `min-height` (option A)

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds a 'Minimum height in pixels' field to the article block, when you have the image positioned in the background. 

It's a starting point for some of the ideas suggested in #153; two other PRs (#196 and #197) illustrate a couple other approaches we could look at. 

The main issue I see with this approach could be mobile: in looking at CoBlock's Hero block, it lets you set a mobile and tablet min-height in pixels separately. However, the way they override the inline desktop height is by adding `!important`, which we can't use with AMP. 

I think this is something we need to resolve to some extent before merging -- a 1000px tall article on desktop may make sense, and then look terrible on mobile. But I wanted to put this out there first to see how it feels :) 

### How to test the changes in this Pull Request:

1. Apply the PR and run `npm run build:webpack`
2. Add an article block to a page.
3. Set the article block to use the `Show media behind` image position.
4. Confirm you now have a field in the Featured Image Settings labelled 'Minimum height in pixels':

image

5. Try setting it to a variety of settings, and make sure they're respected on the front-end and in the editor.
6. Make sure the minimum height isn't applied to an article in the set that doesn't have a featured image.
7. Try hiding the featured image; make sure the 'Minimum height' option is hidden, and the height is no longer applied.
8. Try changing the image positioning to top, left, or right, and make sure the 'Minimum height' option is hidden, and the height is no longer applied. 
9. Give some feedback on how to approach this for mobile (please and thank you!). 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### CODE REVIEW

**Review by thomasguillot — COMMENTED** [review]
I feel like this option doesn't offer as much flexibility as the other two, especially on mobile. If you set the min-height to 1000px, then it looks huge on mobile whereas the vh approach looks a bit more balanced.

Maybe adding options for mobile/tablet would make it more flexible, but is it worth the effort?

Nov-01-2019 16-32-14

**Comment by thomasguillot** [comment]
If we go ahead with this. Icons that I would suggest:

* Desktop: https://fonts.gstatic.com/s/i/materialicons/desktop_windows/v1/24px.svg
* Tablet: https://fonts.gstatic.com/s/i/materialicons/tablet/v1/24px.svg
* Mobile: https://fonts.gstatic.com/s/i/materialicons/smartphone/v1/24px.svg

**Comment by laurelfulford** [comment]
Yeah, I definitely agree that it's less flexible than the other two.

The issue I ran into offering three heights -- desktop, mobile and tablet -- is more _how_ to add the styles. CoBlocks adds the min-height inline for the desktop styles, but if you add a mobile and tablet height, it'll generate a unique CSS class and those styles to the `head`, like:

```<style id='coblocks-frontend-inline-css' type='text/css'>
@media only screen and (max-width: 768px) {
        .coblocks-hero-101111828337 > [class*="__inner"]:not(.is-fullscreen) {
                min-height:300px !important
        }
}

@media only screen and (max-width: 514px) {
        .coblocks-hero-101111828337 > [class*="__inner"]:not(.is-fullscreen)  {
                min-height:400px !important
        }
}
</style>```

Since AMP ignores `!important`, we wouldn't be able to do exactly this; we'd probably have to always generate unique classes and add styles for all three to the `head`. So yeah, definitely more effort; it might be best to start with one of the other approaches, and if there's a call for this level of control, build on top of that.

**Comment by thomasguillot** [comment]
Ok, thank you for the explanation @laurelfulford. I've only realised you already mentioned this in the description of the PR  🤦‍♂ 
Alright so, I think we should disregard this option.

**Comment by laurelfulford** [comment]
Haha it's okay! That comment was buried in multiple paragraphs, I should've highlighted it more as a concern. 

Closing this approach due to lack of flexibility for different sized screens.

**Pull request closed without merging**
