### PR TITLE
fix: currency symbol handling

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://github.com/Automattic/newspack-plugin/issues/235.

### How to test the changes in this Pull Request:

1. On `master`, choose "Uzbekistani som" as the currency in Reader Revenue wizard
2. Visit a page with a Donate block, observe the money input (when chosen "Other" as the amount) displays the currency symbol and input in two separate lines
3. Switch to this branch, rebuild, observe issue resolved

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
The new rules are being applied only for `.tiered` donate blocks, they could be replicated to work with the `.untiered` block, but I believe it makes sense applied to [all `money-input` elements](https://github.com/Automattic/newspack-blocks/blob/36cbd88c24cfeef39e4dac3e01ae82739b1cb2b7/src/blocks/donate/view.scss#L166).

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
As the linter already accused, there's already a [selector for .wpbnbd .money-input](https://github.com/Automattic/newspack-blocks/blob/36cbd88c24cfeef39e4dac3e01ae82739b1cb2b7/src/blocks/donate/view.scss#L166) that should be prioritized for the new rules.

**Comment by adekbadek** [comment]
Fixed in 44ac1ed04bb21202af3cf1233db956ee3be82c77 👌

**Review by miguelpeixe — APPROVED** [review]
💯

**Pull request merged**
