### PR TITLE
Generate separate editor assets per each block

### PR DESCRIPTION
**Pull request by marekhrabe**
### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Apart from the combined build of all the blocks together (current usage), this makes them also available as individual JS & CSS files.

This makes it easier to enqueue assets for a single block and a possibility to publish single blocks, as that currently looks like the future of blocks in WP.org block repo.

Closes # .

### How to test the changes in this Pull Request:

0. `npm install`
1. `npm run build:webpack`
2. Explore the `dist` folder generated
3. You show now see additional files - for example `dist/homepage-articles/editor.{js,css,rtl.css,deps.json}`

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by marekhrabe** [comment]
It was quite easy to split the frontend parts but what about the PHP? Can we also cleanly separate it plugin-by-plugin or is there too much shared stuff and connective tissue?

**Comment by marekhrabe** [comment]
Things I'm exploring further:

- block assets are enqueued though non-standard way (using for example `Newspack_Blocks::enqueue_view_assets`). Updating it to use the standard Gutenberg way would loosen the requirement to have the shared class
- Homepage Articles require (I _think_) some additional things in the API, however the code is separated from the block - https://github.com/Automattic/newspack-blocks/blob/61217f85fcef2f108afd293a20cca8b15707df80/class-newspack-blocks-api.php#L16-L58 - maybe we can collocate?

**Comment by obenland** [comment]
This looks like a pretty safe, backwards compatible step forward. I like it.

> block assets are enqueued though non-standard way (using for example Newspack_Blocks::enqueue_view_assets). Updating it to use the standard Gutenberg way would loosen the requirement to have the shared class

Yeah, I wonder if it would make sense to add reusable php file (and readme) where we could replace placeholders to bundle with the assets you generate here.

> Homepage Articles require (I think) some additional things in the API, however the code is separated from the block

This could be broken out and bundled with the block?

**Comment by getdave** [comment]
I'm really sorry but I accidentally marked this as `Ready for Review` cos I clicked the wrong UI button in Github!!! 😭

**Comment by marekhrabe** [comment]
This one is sooo not ready 😀

**Pull request closed without merging**
