### PR TITLE
AMP compatibility for home page article block

### PR DESCRIPTION
**Pull request by philipjohn**
This change removes the view.js and related enqueueing code to ensure AMP compatibility. When using the homepage articles block, the enqueueing of view.js, which has `wp-polyfill` as a dependency, breaks AMP compatibility because of the polyfill scripts inserted by WordPress core.

Without view.js the homepage articles block still works as expected.

### CODE REVIEW

**Comment by jeffersonrabb** [comment]
Rather than removing entirely, I'd prefer we exclude `view.js` based on being in an AMP environment. Even though the homepage articles block doesn't require any view-side scripting there may be others in the future that do, there may be situations where a block requires these scripts in non-AMP environments, and we want to keep open the possibility that these blocks can be used outside of Newspack. Here's Jetpack's AMP environment check: https://github.com/Automattic/jetpack/blob/master/3rd-party/class.jetpack-amp-support.php#L56-L72

**Comment by philipjohn** [comment]
As an in-between could we only include view.js once we start needing it, and introducing the AMP check at that point? At the moment, it seems like view.js is unnecessary regardless of AMP compatibility (or I might be missing something).

There are possibly other alternatives too:

1. Do we need `wp-polyfill` as a dependency at all?
2. Can we use `amp-script`?

**Comment by jeffersonrabb** [comment]
Alternate approach proposed here: https://github.com/Automattic/newspack-blocks/pull/20

**Comment by philipjohn** [comment]
Closing in favour of #20

**Pull request closed without merging**
