### PR TITLE
fix(wc-subs-limiting): handle not-logged-in user

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

A hotfix.

Amends #1728 to handle not-logged-in users, assuming their user ID from the email provided at checkout.

### How to test the changes in this Pull Request:

1. Create or edit a subscription product – in the Advanced settings section, add limiting:

image

3. Purchase the subscription, then log out and purchase it again with the same email address 
4. Observe the second subscription cannot be bought

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207914048664948

### CODE REVIEW

**Review by dkoo — CHANGES_REQUESTED** [review]
This functionally works well, but the error message isn't very helpful and also includes a link to the Shop page, which doesn't play well with the modal checkout iframe. Let's see if we can make this a bit more user-friendly

Screenshot 2024-08-05 at 2 19 21 PM

**Comment by dkoo** [comment]
6d40ff75 adds some filtering to make the error messaging a little clearer and more contextual when limiting purchase in the modal checkout:

Screenshot 2024-08-05 at 3 34 57 PM

**Review by leogermani — APPROVED** [review]
Looks and work well!

**Comment by adekbadek** [comment]
Assuming @dkoo 's contributions amount to an approval :)

**Pull request merged**
