### PR TITLE
feat: submit checkout form on "Enter" keypress

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Allows an "enter" keypress to submit the checkout form, to maintain parity with `trunk`.

### How to test the changes in this Pull Request:

1. Check out this branch
2. Start a modal checkout.
3. Focus on the form by clicking into an input field and press "enter". Confirm that it submits the form and returns any applicable errors (e.g. for required fields)
4. Fill out all fields and hit "enter" again. Confirm that the checkout modal proceeds to the payment form.
5. Confirm that you can submit the payment form by hitting "enter" too.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by adekbadek — COMMENTED** [review]
On this branch (as opposed to `epic/ras-acc`), the modal checkout does not load. There is an `Cannot read properties of undefined (reading 'slice')` JS error in the console, originating from [this line](https://github.com/Automattic/newspack-blocks/blob/634ed0fcd309f9ccb35c0b974cac266183dcd3d2/src/modal-checkout/index.js/#L455). Something's not right with the form events.

**Comment by dkoo** [comment]
@adekbadek hmm, I'm unable to replicate this error, but I was able to simplify the handler in b0a2771e. Does that fix it for you?

**Comment by dkoo** [comment]
Ah, I see! This is happening in Firefox only. Fix incoming...

**Comment by dkoo** [comment]
@adekbadek 14e34ac3 fixes the error for me in Firefox. Does it for you?

**Review by adekbadek — APPROVED** [review]

**Pull request merged**
