### PR TITLE
Avoid Post Duplication (View Only)

### PR DESCRIPTION
**Pull request by jeffersonrabb**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR is an attempt to ensure that multiple articles blocks on the same page will not show the same post more than once. Some questions and caveats:

- This PR only affects the view (preview/published content). In the editor there will still be duplicate posts. This will be addressed in a separate PR.
- Currently this logic will be applied to every instance of `Newspack Homepage Articles` block. Would we need the flexibility to exempt certain blocks from the logic? 
- Blocks will be processed in the order they appear on the page, with higher prioritized stories going to the first ones. It is possible that an unusual layout could be produced where the topmost block is not the visually dominant one, which could lead to unexpected distribution of posts.

This is a partial resolution of https://github.com/Automattic/newspack-blocks/issues/12

### How to test the changes in this Pull Request:

1. Add a few instances of the block to a post or page, with identical query settings.
2. Observe there are duplicate posts visible in the Editor.
3. Publish or preview. Observe that there is no duplication.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by jeffersonrabb** [comment]
> I looked into using offset instead of oversized posts_per_page (for much better performance), but I wasn't able to figure out how to make it work nicely when there are homepage blocks with categories. 

I tried this approach too, but as you say it only really works if all blocks use the exact same query, which they won't. Do you think the oversized `posts_per_page` will be a significant drag? I was under the impression this won't be too costly, and the most important thing was to avoid using `post__not_in`, which is the primary rationale for the approach used here.

**Comment by claudiulodro** [comment]
Good sleuthing. I think the issue may be as simple as [this being an off-by-one error](https://github.com/Automattic/newspack-blocks/pull/61/files#diff-0bc1373b8d23b0320f8a67d468c37a1eR67)?

e.g. 
```
$posts_to_show = intval( $attributes['postsToShow'] ); // Let's say postsToShow = 1
$post_counter = 0

// Show posts until $post_counter > $posts_to_show
// Display a post. $post_counter is now 1. Go again since $post_counter > $posts (1 > 1) is false.
// Display a post. $post_counter is now 2. $post_counter > $posts, so stop showing posts. 2 posts were displayed and we requested only 1.
```

**Comment by jeffersonrabb** [comment]
Nice sleuthing both of you! This should fix it: https://github.com/Automattic/newspack-blocks/pull/61/commits/365d8d1673a4b741145cc99d0b53be5bcfd91538

**Comment by laurelfulford** [comment]
Looks good to me! I turned my front page into a dumpster fire of multi-category posts; there aren't any dupes, and the post counts are right; parsing through the /wp-admin posts screen, it looks like everything is displaying in order and where expected. 🎉

**Comment by jeffersonrabb** [comment]
OK! Onward to solving the issue in the editor now...

**Comment by iamtakashi** [comment]
> Onward to solving the issue in the editor now...

Could you let me know where this work is happening? The difference between the editor and the front-end of the site is very confusing at the moment. cc @Automattic/ajax

**Comment by jeffersonrabb** [comment]
> Could you let me know where this work is happening?

This editor de-duplication work is occurring in https://github.com/Automattic/newspack-blocks/pull/176 which is a  different block. It's conceivable the work in that block could be applied to Homepage Articles, but this isn't being actively explored at the moment. This is the commit where editor de-dupe was first introduced: https://github.com/Automattic/newspack-blocks/pull/176/commits/672ff1903cde3e5f68af2a955eafc5a87e93d57c

cc: @georgeh

**Pull request merged**
