### PR TITLE
fix: avoid duplicity with linked guest authors

### PR DESCRIPTION
**Pull request by leogermani**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes an issue with CAPs linked authors in the Hompepage posts block

### How to test the changes in this Pull Request:

1. Create a user and a guest author that share the same name
2. Create one post authored by each of these users
3. Edit the guest author and link them to the user with the same name
4. On `master` add a new Homepage block to a page and search for the author by it name in the "authors" filter box
5. Confirm you get two results
6. Checkout this branch
7. Confirm you now get only one result
8. Confirm the posts are queried correctly and you get both posts rendered in the block

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204817890713184

### CODE REVIEW

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
I was not able to reproduce the issue this is trying to fix. My steps on the master branch were:

- Created a user "Jane Doe"
- Created a guest user "Jane Doe" 
- Created a "Jane Doe Post" and selected both users as author
- Edited guest user "Jane Doe" to map to the user with the same name
- Created a homepage posts block to filter only "Jane Doe" and this is what I got:

image

I edited the created post and was surprised to see that the post no longer had 2 authors. I suspect CAP resolved that when the GA was mapped.

Looking into the original issue in Asana, I believe the problem might be related to how the [`AutocompleteTokenField`](https://github.com/Automattic/newspack-blocks/blob/a0040b43a3f97c889e5bb5b5b96f07777b52a670/src/components/query-controls.js#L278-L284) behaves.

[The component "tokens" are the input labels](https://github.com/Automattic/newspack-blocks/blob/a0040b43a3f97c889e5bb5b5b96f07777b52a670/src/components/autocomplete-tokenfield.js#L155-L163), so you are not able to select multiple items that share the same name. I believe this should be resolved in 2 ways (not exclusively):
- Append a unique value to the input label, e.g. `Jane Doe (#{id})`
- Prevent mapped users from rendering as an option, so you get only one option

**Comment by leogermani** [comment]
> Created a homepage posts block to filter only "Jane Doe" and this is what I got:

What should happen is that you will see both Janes in the dropdown. If they are not linked, that's expected, but if they are linked you should see only one.

Good idea adding the ID in the label, I'll have a look. But let me know if you can reproduce the above - and confirm the fix

**Comment by miguelpeixe** [comment]
I just realized that I completely misinterpreted the PR 😅 

I thought it was duplicating posts and not the authors' names. I now understand what to test.

**Review by miguelpeixe — APPROVED** [review]
Now that I understand what to test I can confirm it's working as described!

The addition to the unique value on the label would be nice but not a blocker for this.

**Comment by dkoo** [comment]
Screenshot 2023-12-22 at 11 00 06 AM

Those sneaky guest authors... 🕵️

**Comment by leogermani** [comment]
> Screenshot 2023-12-22 at 11 00 06 AM
> 
> Those sneaky guest authors... 🕵️

oops, sorry for my english. Miguel got it because we speak the same language :)

**Comment by miguelpeixe** [comment]
I'd never question the use of "duplicity" to mean duplicate 😆

**Comment by dkoo** [comment]
I got what you meant, too. I actually had to look it up because I wasn't sure if my hunch was correct. 🤣

**Pull request merged**
