### PR TITLE
feat: add support for Newspack Guest Contributor in HPP blocks

### PR DESCRIPTION
**Pull request by leogermani**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds support for the Newspack's Guest Contributor role in the Homepage posts and Carousel blocks

### How to test the changes in this Pull Request:

1. Create a user with only the Guest Contributor role and assign a post to it
2. Add a Home page posts block
3. Search by that author name and confirm it finds the author and their posts
4. Do the same for the Carousel block

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — CHANGES_REQUESTED** [review]
I'm not sure why it's happening, but when I have ElasticSearch enabled for HPP and Carousel blocks the posts aren't getting fetched for me on the front-end. It works as expected in the editor:

Screenshot 2024-11-04 at 2 37 00 PM

But the front-end shows 0 posts for both blocks. I confirmed that the query args are the same in both contexts, and I only have a single Guest Contributor user who's assigned to a single post (but these were created/assigned many weeks ago, so they should be indexed for ElasticSearch by now). Paging @miguelpeixe who worked on the ES integration in case it's obvious to you.

**Comment by leogermani** [comment]
Looks like requests in the admin are not offloaded to ES.

I'm struggling to test this. @miguelpeixe could you have a look?

**Comment by leogermani** [comment]
@dkoo To be fair, this PR does not touch the Query for posts. It only touches the query for authors in the Authors filter input...

**Comment by miguelpeixe** [comment]
> Paging @miguelpeixe who worked on the ES integration in case it's obvious to you.

~~That was an issue in the first implementation of the ES, which has been fixed since https://github.com/Automattic/newspack-manager/pull/275. Can you confirm you have the latest manager?~~

I may have misunderstood the issue. It works in the editor but on the front-end. If you have ES enabled for Newspack Blocks that might be a new uncovered incompatibility. We should flag that in Asana for further exploration.

**Comment by miguelpeixe** [comment]
> It only touches the query for authors in the Authors filter input...

The ES incompatibility might be in `trunk`, to any query filtering CAP authors.

**Comment by leogermani** [comment]
> > It only touches the query for authors in the Authors filter input...
> 
> The ES incompatibility might be in `trunk`, to any query filtering CAP authors.

They are not CAP authors. It's just another user role. But they are regular wp users

**Comment by leogermani** [comment]
> I may have misunderstood the issue. It works in the editor but on the front-end. 

afaik queries are not offloaded to ES in the admin, only in the front end

**Comment by leogermani** [comment]
@dkoo can you have a look again, without the ES integration? I've updated this branch with the latest trunk, there were some fixes there. Things work ok on my end.

I'll work on another PR to make sure that the queries that have the SQL statement filtered will not be offloaded to ES.

EDIT: actually it was a one liner so I added in https://github.com/Automattic/newspack-blocks/pull/1934/commits/1d1b168a88cb9b73eaf7ef4f0d6f4bad98526c37 - depends on https://github.com/Automattic/newspack-manager/pull/301

**Review by dkoo — APPROVED** [review]
Working now with https://github.com/Automattic/newspack-manager/pull/301!

**Comment by dkoo** [comment]
@leogermani looks like we need to account for the new query param in the unit tests

**Comment by leogermani** [comment]
> @leogermani looks like we need to account for the new query param in the unit tests

Fixed

**Pull request merged**
