### PR TITLE
Adds first pass at a 'background image' style for the block.

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds a 'background image' style to the block; if a story has a featured image, it will be used as a background, and the text inside of the block will be set to white. 

I'm curious what other options could be helpful for this block. I'm thinking height/padding, or vertical alignment could help with placing the text at the top/bottom, or left/right; there's probably more.

Related to #43

### How to test the changes in this Pull Request:

1. Apply the PR and run `npm run build:webpack`.
2. Add a newspack block; make sure at least some of the articles in it have featured images.
3. In the style switcher, pick 'Background Image':

image

4. Confirm that the featured image is set as the background, and the text is overlaid and white:

image

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### CODE REVIEW

**Comment by rickybanister** [comment]
Beautiful!

I agree that the text alignment options would add more code-free flexibility, but this is already going to be super useful as is.

**Comment by laurelfulford** [comment]
Thanks @rickybanister! 

I'll set this to 'needs review' to get some eyes on the code, and if it goes in as is we can iterate on it.

**Review by jeffersonrabb — COMMENTED** [review]
If Newspack Theme is current and custom colors are in use, the author name turns dark (this is not actually one of the theme colors). Also, in non-columnar layouts perhaps we need a `min-height`?

Screen Shot 2019-08-19 at 11 50 54 PM

**Comment by rickybanister** [comment]
I don't know if we need a min-height, that could be just as frustrating in some other contexts as not having one here. Maybe we provide a height slider sidebar option? And maybe eventually we could provide a handle on the image itself to pull the block taller like the proposed column and image adjustment UIs? 

Regarding the author style, do we just need to add more specificity to override the custom color?

**Comment by laurelfulford** [comment]
> Also, in non-columnar layouts perhaps we need a min-height?
> Maybe we provide a height slider sidebar option? 

I agree we need some way to control the height, and probably a base-line min height -- right now, assuming it's not displaying as a grid, the height is determined by the amount of text inside. 

I think it would also be good to be able to align things left, right, up, down, but that's kind of getting ahead of things :) 

One challenge is that, as far as I know, you can't conditionally show/hide controls based on block style (like you can with other toggles -- like showing/hiding the featured image-related controls based on whether the images are actually displaying). 

So we may always have to show the height controls, or perhaps have to move this very-style-like control to a non-style placement (like as one of the image alignment options, or to the sidebar). 

@jeffersonrabb & @rickybanister - I'd be really interested in your thoughts on the above!

**Comment by rickybanister** [comment]
The image alignment options makes sense to me actually—we could provide options for 'crop to text' or 'full size image' and show the image in its native aspect ratio?

**Comment by laurelfulford** [comment]
I've updated the block so that the 'background image' option is one of the image alignment options -- I also realized that it, as a style, would clash with the left and right options, so it really does make sense to have it there instead.

For the time being, I used a pretty weak icon (below) but it works for now as a placeholder:

image

I also added some padding to the top, and aligned the text to the bottom, but I think we really do need some kind of control to adjust depending on how large the block is -- a v2? 

> we could provide options for 'crop to text' or 'full size image' and show the image in its native aspect ratio?

I think it should be doable, but that might need to be a v3, 4 and 5 :)

**Comment by rickybanister** [comment]
That all sounds right to me. Maybe we should just use the image icon to represent this style since it's image-dominant?

**Comment by laurelfulford** [comment]
> Maybe we should just use the image icon to represent this style since it's image-dominant?

Oh, I like that better! I updated it in 7c1af2c:

image

Right now I'm just using the dashicons that are immediately available; we could also replace it with a more appropriate SVG once we track one down :)

**Comment by laurelfulford** [comment]
I made an update to this PR in 4e6eb9a, adding the top-padding slider, since it seemed important for this style to actually be usable. 

I ranges from 1 to 12, and each value has a padding based on screen size, following the same pattern:

* For `4`, it's `2em` on mobile, `4em` on tablet, and `8em` on desktop.
* For `6`, it's `3em` on mobile, `6em` on tablet, and `12em` on desktop.
* For `10`, it's `5em` on mobile, `10em` on tablet, and `20em` on desktop.

... etc.

**Review by jeffersonrabb — CHANGES_REQUESTED** [review]
I'm getting a white bar (white text on a white background) for the title when testing this.

Screen Shot 2019-10-08 at 12 29 27 AM

**Comment by laurelfulford** [comment]
Ah, foiled by Style 3 again! 

It looks like I'll need to add a complementary PR for that style pack to make sure this doesn't happen (similar to how it's being handled when the article block is nested inside of a cover block). 

I'll circle back shortly with a PR for the theme to test with this, and make sure it's resolved.

**Comment by laurelfulford** [comment]
There's an update for style 3 that can be tested with this PR here:

**Comment by laurelfulford** [comment]
In testing the above, I also noticed there's an issue with `object-fit: cover` + AMP.

(This also happens for two of the theme featured image styles, the behind and beside options.)

I found this fix for an object fit issue in Twenty Nineteen that we might want to explore: https://github.com/ampproject/amp-wp/pull/1619/commits/4fb548aa8883a9fd80c7849fb74e51cf5edb8366

**Comment by laurelfulford** [comment]
Ok, the above is fixed in 4e211a9  -- thanks for the big assist, @jeffersonrabb!

**Comment by laurelfulford** [comment]
@jeffersonrabb as per our convo in Slack, I've removed the padding control in 560d5db for now, so we can handle it in a separate PR and explore some other approaches before sticking with this one.

One other thing that's changed since this PR was created: we can now show the image caption in each block :| That could be something else to mull over approaches for after this PR is merged. I'm leaning towards hiding it and the option to show it entirely when this image position is picked, but there might be a better approach!

**Review by jeffersonrabb — APPROVED** [review]
This is good to go. Thanks for your patience on this one!

**Comment by laurelfulford** [comment]
Thanks Jeff!

> Thanks for your patience on this one!

Not a problem! I appreciate that you have reserve to step back and rethink approaches like this -- I get so swept up in solving the problem sometimes, I run with the first solution I see without considering the ways we could end up "stuck" with it. :) 

I'll create a separate issue in which we can hash the scaling question and the captions questions out!

**Pull request merged**
