### PR TITLE
Homepage Posts: Improve Specific Posts UI

### PR DESCRIPTION
**Pull request by jeffersonrabb**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR improves two aspects of the Specific Posts UI:
- The feature toggle was labelled "Choose specific stories," not "Posts."
- Feedback indicated the post selection autocomplete interface was not immediately apparent, and help text would be useful. 

Closes https://github.com/Automattic/newspack-blocks/issues/310.

Screen Shot 2019-12-24 at 9 54 43 AM

### How to test the changes in this Pull Request:

1. Verify the field is labelled `Choose Specific Posts`
2. Toggle the field on and verify helper text below the input.
3. Verify Authors/Categories/Tags inputs no longer have help text beneath them.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by jeffersonrabb** [comment]
Thanks for reviewing!

**Comment by thebud15** [comment]
@jeffersonrabb Sorry for missing your ping [here](https://github.com/Automattic/newspack-blocks/issues/310#issuecomment-568492750). Looks like this all got sorted!

**Comment by thebud15** [comment]
@jeffersonrabb has this been universally applied? If you look at the site from #2720396-zen, you may notice that I did... That the homepage has a Blog Posts block with the "Stories" label still.

**Comment by jeffersonrabb** [comment]
> @jeffersonrabb has this been universally applied? If you look at the site from #2720396-zen, you may notice that I did... That the homepage has a Blog Posts block with the "Stories" label still.

I don't believe it has. There is an open PR to sync recent changes, but it is still open as of now: https://github.com/Automattic/wp-calypso/pull/39270/. @obenland any sense of when the sync may land?

**Comment by obenland** [comment]
It's been dragging on, hoping to include a fix for https://github.com/Automattic/newspack-blocks/issues/306. Unfortunately it looks like that'll take a while longer.

@jeffersonrabb Do you want to release a .26? I can then update the merge PR and get it in.

**Comment by jeffersonrabb** [comment]
> @jeffersonrabb Do you want to release a .26? I can then update the merge PR and get it in.

On our end there's nothing new since .25 so you're good to go with that release.

**Pull request merged**
