### PR TITLE
Build Description Overrides

### PR DESCRIPTION
**Pull request by jeffersonrabb**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR refactors most of the Webpack Config so that exactly what is built is determined by a JSON file (`build-description.json`) and the settings can be overridden by creating an alternate JSON file and passing its path in as a parameter. This approach allows for the following  scenarios:

- Build the plugin with only one block included.
- Build the plugin with a subset of block extensions included. This subset can be empty if these aren't needed.
- Ignore or replace the editor and view setup files.
- Ignoring the editor setup file removes the Newspack block category.
- An alternate editor setup file  can be used to apply the `registerBlockType` filter to one  of  the  Newspack blocks, which allows overwriting the block title, category, and registration name (among other things).
- This PR also  adds filters to override the block registration names in the server-side renderer. If the block registration is altered using the `registerBlockType` approach it will also need to be overridden in  the PHP classes using these filters. 

#### Verify normal behavior
1. Run `npm run start` normally.
2. Verify the Newspack block category exists and contains `Newspack Homepage Articles`, `Donate`, and `Carousel`.
3. Test all three blocks and make sure they are functioning normally in the editor and view.
4. Verify all block extensions are working normally in the editor and  view. These apply to `Columns`, `Column`, and `Group` blocks.

#### Verify overrides
1. At the root of the repo,  create an uncommitted file named `build-description-overrides.json` with the following contents:

```
{
  "blocks_development": [ "homepage-articles" ],
  "blocks_production": [ "homepage-articles" ],
  "block_extensions_development": [],
  "block-extensions_production": []
}
```
2. Execute  `npm run start --build-description=./build-description-overrides.json`. 
3. Verify in the  editor the Newspack block category contains only `Newspack Homepage Articles`.
4. Verify all of the block styles and extensions are absent. One way to do  this is to add `Columns` and check that the block  styles `Borders`, `Move first column to second`, and `Move first column to third` aren't there.
5. Update  `build-description-overrides.json` to:
```
{
  "blocks_development": [ "homepage-articles" ],
  "blocks_production": [ "homepage-articles" ],
  "block_extensions_development": [],
  "block-extensions_production": [],
  "setup_editor": "./setup.js",
}
```
6. Create a new file at  the root of the repo  called `setup.js`:
```
import { addFilter } from '@wordpress/hooks';
addFilter( 'blocks.registerBlockType', 'newspack-blocks', ( settings, name ) => {
	if ( name === 'newspack-blocks/homepage-articles' ) {
		return {
			...settings,
			name: 'a8c/fancy-posts',
			title: 'Fancy Posts',
			category: 'common',
		};
	}
	return settings;
} );

```
7. Execute  `npm run start --build-description=./build-description-overrides.json` again.
8. Verify any existing instances of the block  show the Gutenberg invalid error, since the name  has changed.
9. Verify the block has been renamed `Fancy Posts`, appears in the `Common` category, and functions  normally (in the editor).
10. In a published post, the new block will fail, since the server-side rendering code assumes the name `newspack-blocks/homepage-articles`. To fix this, add this filter to any of the PHP files (e.g. `newspack-blocks.php`:
```
add_filter(
	'newspack_blocks_homepage_articles_type',
	function( $tag ) {
		return 'a8c/fancy-posts';
	}
);
```
11. Verify the block now works properly in  published posts.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by jeffersonrabb** [comment]
@laurelfulford would you mind running through this one without any of the override stuff to verify that all of the block styles and extensions to core blocks are working  normally?

**Comment by jeffersonrabb** [comment]
Putting this on hold for the moment. @marekhrabe is exploring  an alternate approach where WPCOM/FSE integration would not use `newspack-block`'s build process. If that solution works out, then the immediate need for this PR  goes away.

**Comment by retrofox** [comment]
**Verify normal behavior**

- [x] Run npm run start normally. ✅ 
- [x] Verify the Newspack block category exists and contains Newspack Homepage Articles, Donate, and Carousel. ✅ 



- [ ] Test all three blocks and make sure they are functioning normally in the editor and view.
- [ ] Verify all block extensions are working normally in the editor and view. These apply to Columns, Column, and Group blocks.

**Comment by jeffersonrabb** [comment]
Unnecessary for now. Closing.

**Pull request closed without merging**
