### PR TITLE
refactor: render custom excerpt length server-side

### PR DESCRIPTION
**Pull request by jeffersonrabb**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The custom excerpt length control introduced in https://github.com/Automattic/newspack-blocks/pull/607 had one drawback, which is that `the_excerpt is no longer filtered in the editor.` This has come up in https://github.com/Automattic/newspack-blocks/issues/700 as a problem for blocks with fallback content. The custom posts endpoint introduced in https://github.com/Automattic/newspack-blocks/pull/661 opens up a cleaner way to deal with this problem. In this PR, the block excerpt length and visibility attributes are passed to the endpoint and the endpoint uses excerpt filtering identical to the block's front-end rendering. This should also mean the truncated excerpt is _slightly_ more WYSIWYG since the editor and front-end are now using the exact same approach.

Closes https://github.com/Automattic/newspack-blocks/issues/700

### How to test the changes in this Pull Request:

1. Add a few Homepage Posts blocks to a post, toggle on `Show Excerpt` on some of them, and try a variety of `Max number of words in excerpt` settings.
2. Verify the results seen in the editor match the results seen in front end.
3. On `master`, replicate the issue described in https://github.com/Automattic/newspack-blocks/issues/700 using a block with fallback content (Podcast Player or Eventbrite Checkout). 
4. Switch to this branch, verify the issue is resolved.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by creativecoder — COMMENTED** [review]
@jeffersonrabb Thank you for the quick fix.

✅ This change fixes #700 and I seems like a much cleaner way to display the excerpt in the editor!

One more improvement I think would be good before merging this is debouncing the excerpt length change. As is, a lot of requests can be triggered while adjusting the range slider:

newspack-post-requests-when-changing-excerpt-length

**Comment by adekbadek** [comment]
> One more improvement I think would be good before merging this is debouncing the excerpt length change. As is, a lot of requests can be triggered while adjusting the range slider

Good catch! It appears that these are actually the preview blocks in the "Styles" tab making these requests; the requests made by the block "in the editor" are using the `newspack-blocks/v1/newspack-blocks-posts` endpoint (and have debouncing in place).

**Comment by adekbadek** [comment]
@creativecoder debounce added in b5824c9 👍

**Review by adekbadek — APPROVED** [review]

**Review by dkoo — APPROVED** [review]
Works as described 👍

**Pull request merged**
